services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra_waste
    environment:
      - CASSANDRA_CLUSTER_NAME=wastemanagement
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
    ports:
      - "9042:9042"
    networks:
      - cassandra-net
    volumes:
      - cassandra-data:/var/lib/cassandra
    restart: always
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "DESCRIBE KEYSPACES"]
      interval: 30s
      retries: 5
      start_period: 10s

  basex:
    image: basex/basexhttp:latest
    container_name: basex_waste
    ports:
      - "8984:8984" 
      - "1984:1984" 
    networks:
      - cassandra-net
    volumes:
      - basex-data:/basex/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8984 || exit 1"]
      interval: 30s
      retries: 3
      start_period: 10s
  
  postgres:
    image: postgres:latest
    container_name: postgres__waste
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=admin
    ports:
      - "5433:5432"
    networks:
      - cassandra-net
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      retries: 3
      start_period: 10s

  mysql:
    image: mysql:latest
    container_name: mysql-water
    environment:
      - MYSQL_ROOT_PASSWORD=root  
      - MYSQL_DATABASE=water_sql 
      - MYSQL_USER=admin            
      - MYSQL_PASSWORD=admin      
    ports:
      - "3307:3306" 
    networks:
      - cassandra-net 
    volumes:
      - mysql-data:/var/lib/mysql 
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
  mongodb:
    image: mongo:latest
    container_name: mongodb_water
    environment:
      - MONGO_INITDB_ROOT_USERNAME=not sharing
      - MONGO_INITDB_ROOT_PASSWORD=not sharing
    ports:
      - "27017:27017"
    networks:
      - cassandra-net
    volumes:
      - mongodb-data:/data/db
    restart: always
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      retries: 3
      start_period: 10s
  webapp:
      build:
        context: ./website  
      container_name: water_quality_web
      ports:
        - "8081:80"  
      networks:
        - cassandra-net  
      volumes:
        - ./website:/usr/share/nginx/html  
      restart: always

networks:
  cassandra-net:
    driver: bridge

volumes:
  cassandra-data:
  basex-data:
  postgres-data:
  mysql-data:
  mongodb-data:
